Calendar/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    resources :users
    resources :my_meetings
    resources :meetings

  root to: 'my_meetings#index'
    get '/profile', to: 'users#show'
    get '/profile', :action=>"show", :controller=>"devise/users"
    get '/my_meetings', :action=>"index", :controller=>"my_meetings"
    get '/meetings', :action=>"index", :controller=>"meetings"
    get '/calendar', :action=>"show", :controller=>"my_meetings"
end

Calendar/app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true

  def in_past?
    start_time < Date.today
  end

  def today?
    start_time.between?(Date.today, Date.tomorrow)
  end

  def actual?
    start_time > Date.today
  end

  def indicated(option)
    case
    when option == 'details'
      details.blank? ? "#{option} is not indicated" : details
    when option == 'place'
      place.blank? ? "#{option} is not indicated" : place
    when  option == 'note'
      note.blank? ? "#{option} is not indicated" : note
    else
      priority.blank? ? "#{option} is not indicated" : priority
    end
  end

  def isPriority?
    priority.nil? ? false : priority > 0
  end
end

Calendar/app/models/user.rb
class User < ActiveRecord::Base
  has_many :meetings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_name?
    name.blank? ? 'Not indicated' : name
  end
end

Calendar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end

  def set_time_zone
      Time.zone = current_user.time_zone
  end
end

Calendar/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @meetings = Meeting.all.order(start_time: :desc)
    @type = request.params[:format]
  end

  def show
  end

  def edit
  end

  def create
   @meeting = current_user.meetings.new(meeting_params)
     respond_to do |format|
       if @meeting.save
         format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
       else
         format.html { render :new }
       end
     end
 end

def update
  respond_to do |format|
    if @meeting.update(meeting_params)
      format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
    else
      format.html { render :edit }
    end
  end
end

def destroy
  @meeting.destroy
  respond_to do |format|
    format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
  end
end

  private
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:name, :user_id, :start_time, :details, :note, :place, :priority)
  end
end

Calendar/app/controllers/my_meetings_controller.rb
class MyMeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @meetings = current_user.meetings.order(start_time: :desc)
    @type = request.params[:format]
  end

  def new
    @meeting = current_user.meetings.new
  end

  def edit
  end

  def show
  end

  def create
    @meeting = current_user.meetings.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to my_meetings_path, notice: 'Meeting was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

 def destroy
   @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
    end
  end

  def update
    respond_to do |format|
       if @meeting.update(meeting_params)
          format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        else
          format.html { render :edit }
        end
    end
  end

  private
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:name, :user_id, :start_time, :details, :note, :place, :priority)
  end
end

Calendar/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def edit
  end

  def update_password
    @user = current_user

    if @user.update_with_password(user_params)
      sign_in @user, :bypass => true
      redirect_to root_path
    else
      render "edit"
    end
  end


  def show
  end

  def update
    @user = current_user
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to @user, notice: 'User\'s information was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
  end
  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :name, :email, :id )
  end
end

Calendar/app/helpers/application_helper.rb
module ApplicationHelper
  def truncate(text, options = {}, &block)
    if text
      length  = options.fetch(:length, 15)

      content = text.truncate(length, options)
      content = options[:escape] == false ? content.html_safe : ERB::Util.html_escape(content)
      content << capture(&block) if block_given? && text.length > length
      content
    end
  end
end

Calendar/app/helpers/meetings_helper.rb
module MeetingsHelper
end

Calendar/app/helpers/my_meetings_helper.rb
module MyMeetingsHelper
end

Calendar/app/helpers/users_helper.rb
module UsersHelper
end

Calendar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Calendar" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <% if user_signed_in? %>
    <nav class="top-bar" data-topbar role="navigation">
       <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#"><%= link_to current_user.email, my_meetings_path %></a>
            </h1>
          </li>
        </ul>
       <section class="top-bar-section">
        <ul class="right">

          <li class=""><a href=""><%= link_to 'Events listing ', my_meetings_path %></a></li>
          <li class=""><a href=""><%= link_to 'All Events ', meetings_path %></a></li>
          <li><a><%= link_to 'Profile', controller: "users", action: "show" %></a></li>

          <li class=""><a href=""><%= link_to 'New Meeting', new_my_meeting_path %></a></li>
          <li class=""><a href=""><%= link_to "Exit", destroy_user_session_path, method: :delete %></a</li>
        </ul>
       </section>
     </nav>
   <% end %>
   <%= yield %>

  </body>
</html>

Calendar/app/views/meetings/_form.html.erb
<head>
  <link href="style.css" rel="stylesheet">
</head>

<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
 <div class="small-6 columns">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :details %> <br>
      <%= f.text_field :details %>
    </div>
    <div class="field">
      <%= f.label :place %> <br>
      <%= f.text_field :place %>
    </div>
    <div class="field">
      <%= f.label :note %> <br>
      <%= f.text_field :note %>
    </div>
    <div class="field">
      <%= f.label :priority %>
      <%= f.text_field :priority %>
    </div>
</div>
<div class="small-6 columns ">
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
      <br><br><br>
  </div>
  </div>
  <br><br><br>


   <div class="actions" align="center">


    <%= f.submit "CREATE MEETING", class: "small secondary button"  %>
    <%= link_to 'return', my_my_meetings_path, class: " small secondary button" %>

   </div>
    <% end %>
</div>
</div>
</div>

Calendar/app/views/meetings/_month_calendar.html.erb
<div class="small-13 small-centred columns  ">
<div class="simple-calendar">

 <p align="left"> <%= link_to "Previous", start_date: date_range.first - 1.day  %></p>
  <p align="center"><%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %></p>
 <p align="right">  <%= link_to "Next", start_date: date_range.last + 1.day  %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

Calendar/app/views/meetings/_social_sharing.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script src="https://apis.google.com/js/platform.js" async defer></script>


<div align="center">
<div align="center" class="g-plusone" data-href="https://dry-island-67830.herokuapp.com"></div><div align="center"><a href="https://twitter.com/share" class="twitter-share-button" data-url="https://dry-island-67830.herokuapp.com" data-size="small">Tweet</a></div>
<div align="center"class="fb-like" data-href="https://dry-island-67830.herokuapp.com" data-width="30" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div><br>
</div>

Calendar/app/views/meetings/edit.html.erb
<div class="row">
<br>
  <br>
    <h2 align="center">Editing Meeting</h2>
    <br>
    <br>
    <%= render 'form' %>
   <div class="field" align="center">
    </div>
  </div>
</div>

<p align="center"><a href="https://github.com/AlinaMoskieva">Moskieva Alina</a></p>

Calendar/app/views/meetings/index.html.erb
<br>
<br>
<h1 align="center"> All events</h1>
<br>
<h3 align="center">On this page you can see all evens of all users of the site. Enjoy it :) </h3>
<br>
<h4 align="center"> Choose form :)</h4>
<p align = "center"><%= link_to 'Calendar', meetings_path("calendar"), class: "button small secondary radius"%> Or
<%= link_to 'list', meetings_path("list"), class: "button small secondary radius" %>
</p>
<br>
<div class="row">
  <div class="small-13 small-centred columns  ">
    <% if @type == "calendar" || @type.nil? %>
      <%= month_calendar events: @meetings do |date, meetings| %>
        <p valign="top" align="center">
          <% count = 0 %>
          <%= link_to date.strftime("%d"), new_my_meeting_path %>
        </p>

        <% meetings.each do |meeting| %>
          <div>
             <% count += 1 %>
             <% next unless count > 3%>
               <ul>
               <li><%= link_to truncate( meeting.name ), meeting %></li>
          </div>
        <% end %>
        <% next unless count > 3 %>
          <li>and <%= count - 3 %> events..</li>
     <% end %>
    </div>
  </div>
  <% else %>
    <div class="row">
      <div class=" small-centred columns ">
        <% @meetings.each do |meeting| %>
          <div class="small-2 large-4 columns end">
            <div class="callout-card primary">
              <div class="card-label">
                <div class="label-text">
                 All
                </div>
              </div>
            <article class="event">
              <div class="event-date" >
                <p class="event-month" ><%= meeting.start_time.strftime("%b")%></p>
                <p class="event-day"><%= meeting.start_time.strftime("%d")%></p>
              </div>
            </article>
            <div class="callout-card-content">
              <h3 class="lead" align="center"><%= truncate (meeting.name) %></h3>
              <h6 class="lead" align="center">By <%= truncate ( meeting.user.email) %></h3>
              <p align="center"><%= link_to 'Show', meeting %>
                <br>
                <% if meeting.user_id == current_user.id %>
                  <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }%>
                <% else %>
                  <br>
                <% end %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
 <br>
<p align="center"><a href="https://github.com/AlinaMoskieva">Moskieva Alina</a></p>

Calendar/app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class="row">
  <div class="small-7 small-centered columns">
    <h3 align="center"> Details of meeting </h3><br><br>
    <div class="field">
       <strong>Name:</strong><br>
       <p align="right"><%= @meeting.name %></p>
    </div>
    <p>
      <strong>Start time:</strong><br>
      <p align="right"> <%= @meeting.start_time.strftime("%H:%M %F") %>
    </p><br>
    <p>
      <strong>Details:</strong><br>
      <p align="right">
        <%=  @meeting.indicated("details") %>
      </p>
    <br>
    <p>
     <strong>Place:</strong><br>
      <p align="right">
        <%=  @meeting.indicated("place") %>
      </p>
    </p>
    <br>
    <p>
      <strong>Note:</strong><br>
      <p align="right">
        <%= @meeting.indicated("note") %>
      </p>
    </p>
    <br>
    <p>
      <strong>Created at:</strong>
      <p align="right">  <%= @meeting.created_at.strftime("%H:%M %F") %><br>
    </p>
    <br>
    <p>
      <strong>Priority</strong>
      <p align="right"> <%= @meeting.indicated("priority") %><br></p>
    </p>
    <% if @meeting.user_id == current_user.id %>
     <p align="center">
       <%= link_to 'Edit', edit_my_meeting_path(@meeting), class: "small secondary button radius" %>
    <% end%>
    <%= link_to 'Back', my_meetings_path, class: "small secondary button radius" %><%= render "social_sharing" %></p>
  </div>
</div>
<p align="center"><a href="https://github.com/AlinaMoskieva">Moskieva Alina</a></p>

Calendar/app/views/my_meetings/_form.html.erb
<head>
  <link href="style.css" rel="stylesheet">
</head>

<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
 <div class="small-6 columns">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, placeholder: "Event's name" %>
    </div>
    <div class="field">
      <%= f.label :details %> <br>
      <%= f.text_field :details,  placeholder: "Event's details"%>
    </div>
    <div class="field">
      <%= f.label :place %> <br>
      <%= f.text_field :place, placeholder: "Event's place" %>
    </div>
    <div class="field">
      <%= f.label :note %> <br>
      <%= f.text_field :note,  placeholder: "Event's note" %>
    </div>
    <div class="field">
      <%= f.label :priority %>
      <%= f.text_field :priority, placeholder: "Event's priority. It's a number." %>
    </div>

</div>
<div class="small-6 columns ">
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
      <br><br><br>
  </div>
  </div>
  <br><br><br><br><br><br><br><br><br>


<div class="small-12 columns">

   <div class="actions" align="center">


    <%= f.submit "CREATE MEETING", class: "small secondary button"  %>
    <%= link_to 'return', my_meetings_path, class: " small secondary button" %>

   </div>
   </div>
    <% end %>
</div>
</div>
</div>

Calendar/app/views/my_meetings/edit.html.erb
<div class="row">
  <br>
  <br>
  <h2 align="center">Editing Meeting</h2>
  <br>
  <br>
  <%= render 'form' %>
  <div class="field" align="center">
  </div>
  <p align="center"><a href="https://github.com/AlinaMoskieva">Moskieva Alina</a></p>
</div>

Calendar/app/views/my_meetings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class=" small-centred columns ">
   <br>
   <h2 align="center"> Your events </h2><br>

   <h5 align="center">On this page you can see your events. Choose form :)</h5>
   <p align = "center">
     <%= link_to 'Calendar', my_meetings_path("calendar"), class: "button small secondary radius"%> Or
     <%= link_to 'list', my_meetings_path("list"), class: "button small secondary radius" %> Or
     <%= link_to 'Show priority list', my_meetings_path("priority"), class: "button small secondary radius" %>
   </p>
   <% if @type == "list" || @type.nil? %>
   <h2 align="center">Today</h2>
    <% count =0 %>
     <% @meetings.each do |meeting| %>
      <% if meeting.today? %>
        <% count += 1 %>
           <div class="small-2 large-4 columns end">
             <div class="callout-card secondary">
                <div class="card-label">
                  <div class="label-text">
                        Now
                   </div>
                 </div>

                <article class="event">
                  <div class="event-date" >
                    <p class="event-month" ><%= meeting.start_time.strftime("%b")%></p>
                    <p class="event-day"><%= meeting.start_time.strftime("%d")%></p>
                  </div>
                </article>

               <div class="callout-card-content">
                 <h3 class="lead" align="center"><%= truncate (meeting.name )%></h3>
                  <p align="center"><%= link_to 'Show', meeting %>
                    <br>
                    <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }%>
                  </p>
               </div>
             </div>
           </div>

       <% end %>
    <% end %>
    <div class=" small-centred columns ">
      <% if count.zero? %>
           <p align="center"><%= link_to "You haven't got events ", new_my_meeting_path %> </p>
      <% else %>
          <p align="center">Total: <%=  count %></p>
      <% end %>
    </div>
   </div>
    <div class=" small-centred columns ">
      <br>
      <br>
       <h2 align="center">Actual events</h2>
      <br>
      <br>
     <% count = 0 %>
      <% @meetings.each do |meeting| %>
       <% if meeting.actual? %>
        <% count += 1 %>
           <div class="small-2 large-4 columns end">
             <div class="callout-card primary">
               <div class="card-label">
                 <div class="label-text">
                    New
                 </div>
               </div>

              <article class="event">
                <div class="event-date" >
                  <p class="event-month" ><%= meeting.start_time.strftime("%b")%></p>
                  <p class="event-day"><%= meeting.start_time.strftime("%d")%></p>
                </div>
             </article>

            <div class="callout-card-content">
              <h3 class="lead" align="center"><%= truncate (meeting.name) %></h3>
              <p align="center">
                <%= link_to 'Show', meeting %>
                 <br>
                <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }%>
              </p>
            </div>
           </div>
          </div>

       <% end %>
      <% end %>
  <div class=" small-centred columns ">
    <% if count.zero? %>
        <p align="center">
          <%= link_to "You haven't got events ", new_my_meeting_path %>
        </p>
    <% else %>
       <p align="center">Total: <%=  count %></p>
    <% end %>
  </div>
 </div>

    <div class=" small-centred columns ">
       <% count =0 %>
      <h2 align="center">History</h2>
      <br>
      <br>
      <% @meetings.each do |meeting| %>
        <% if meeting.in_past? %>
         <% count += 1 %>
           <div class="small-2 large-4 columns end">
              <div class="callout-card alert">
                <div class="card-label">
                  <div class="label-text">
                    Old
                  </div>
                </div>

              <article class="event">
                <div class="event-date" >
                  <p class="event-month" ><%= meeting.start_time.strftime("%b")%></p>
                  <p class="event-day"><%= meeting.start_time.strftime("%d")%></p>
                </div>
              </article>

            <div class="callout-card-content">
              <h3 class="lead" align="center"><%= truncate (meeting.name) %></h3>
              <p align="center">
                <%= link_to 'Show', meeting %>
                  <br>
                <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }%>
              </p>
           </div>
         </div>
        </div>
       <% end %>
     <% end %>
    <div class=" small-centred columns ">
    <% if count.zero? %>
      <p align="center">
        <%= link_to "You haven't got events ", new_my_meeting_path %>
      </p>
    <% else %>
      <p align="center">Total: <%=  count %></p>
    <% end %>
  </div>
 </div>
</div>
<% elsif @type == "calendar" %>
  <div class="small-13 small-centred columns  ">
    <h2 align="center">Calendar</h2>

   <%= month_calendar events: @meetings do |date, meetings| %>
      <p valign="top" align="center">
        <%= link_to date.strftime("%d"), new_my_meeting_path %>
      </p>
      <% meetings.each do |meeting| %>
       <div>
        <ul>
        <li>
           <%= link_to truncate( meeting.name ), meeting %>
        </li>
      </div>
      <% end %>
    <% end %>
<% else %>
  <h2 align="center"> Priority list </h2>
    <% count = 0 %>
       <% @meetings.each do |meeting| %>
         <% if meeting.isPriority? %>
           <% count += 1 %>
               <div class="small-2 large-4 columns end">
                  <div class="callout-card alert">
                    <div class="card-label">
                      <div class="label-text">
                        Pri
                      </div>
                    </div>

                  <article class="event">
                    <div class="event-date" >
                      <p class="event-month" ><%= meeting.start_time.strftime("%b")%></p>
                      <p class="event-day"><%= meeting.start_time.strftime("%d")%></p>
                     </div>
                 </article>

                <div class="callout-card-content">
                  <h3 class="lead" align="center"><%= truncate (meeting.name) %></h3>
                  <p align="center"><%= link_to 'Show', meeting %>
                    <br>
                    <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }%>
                  </p>
               </div>
             </div>
          </div>
       <% end %>
     <% end %>
   <div class=" small-centred columns ">
    <% if count.zero? %>
      <br>
      <br>
      <p align="center"><%= link_to "You haven't got events ", new_my_meeting_path %> </p>
    <% else %>
         <p align="center">Total: <%=  count %></p>
    <% end %>
   </div>
<% end %>
<div class="small-12 columns">
  <p align = "center">
    <%= link_to 'New Meeting', new_my_meeting_path, class: "button small secondary radius" %>
    <br>
    <a href="https://github.com/AlinaMoskieva">Moskieva Alina</a>
  </p>
</div>
<br>

Calendar/app/views/my_meetings/new.html.erb
<br>
<h1 align="center">New Meeting </h1>
<br>
<br>
   <%= render 'form' %>
<br>
<p align="center"><a href="https://github.com/AlinaMoskieva">Moskieva Alina</a></p>

Calendar/app/views/my_meetings/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class="row">
  <div class="small-7 small-centered columns">
    <h3 align="center"> Details of meeting </h3><br><br>
    <div class="field">
       <strong>Name:</strong><br>
       <p align="right"><%= @meeting.name %></p>
    </div>
    <p>
      <strong>Start time:</strong><br>
      <p align="right"> <%= @meeting.start_time.strftime("%H:%M %F") %>
    </p><br>
    <p>
      <strong>Details:</strong><br>
      <p align="right">
        <%=  @meeting.indicated("details") %>
      </p>
    <br>
    <p>
     <strong>Place:</strong><br>
      <p align="right">
        <%=  @meeting.indicated("place") %>
      </p>
    </p>
    <br>
    <p>
      <strong>Note:</strong><br>
      <p align="right">
        <%= @meeting.indicated("note") %>
      </p>
    </p>
    <br>
    <p>
      <strong>Created at:</strong>
      <p align="right">  <%= @meeting.created_at.strftime("%H:%M %F") %><br>
    </p>
    <br>
    <p>
      <strong>Priority</strong>
      <p align="right"> <%= @meeting.indicated("priority") %><br></p>
    </p>
     <p align="center">
    <% if @meeting.user_id == current_user.id %>
       <%= link_to 'Edit', edit_my_meeting_path(@meeting), class: "small secondary button radius" %>
    <% end%>
    <%= link_to 'Back', my_meetings_path, class: "small secondary button radius" %><%= render "social_sharing" %></p>
  </div>
</div>
<p align="center"><a href="https://github.com/AlinaMoskieva">Moskieva Alina</a></p>

Calendar/app/views/users/_form.html.erb
<% @user = current_user %>
<%= form_for(current_user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
       <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <br>
  <div class="actions" align="center">
    <%= f.submit "UPDATE USER", class: " small secondary button" %>
     <%= link_to 'return', user_path(@user.id), class: " small secondary button" %>
  </div>
<% end %>

Calendar/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
 <div class="small-7 small-centered columns">
   <br>
   <h3 align="center"><%= current_user.email %></h3>
   <p>
      <br>
      <strong>Your name:</strong><br>
      <%= current_user.has_name? %>
    </p>
    <br>
    <p>
      <strong>Your email:</strong><br>
      <%= current_user.email %>
    </p>
    <br>
    <p>
      <strong>Your events</strong><br>
      <%= current_user.meetings.size %>
    </p>
    <br>
    <p align="center">
      <%= link_to "Edit user information",edit_user_path(current_user), class: "small secondary button radius" %>
      <%= link_to "Change your password", edit_user_registration_path, class: "small secondary allert button radius" %>

      <%= link_to 'Back', meetings_path, class: "small secondary button radius" %>
    </p>
<p align="center">
  <a href="https://github.com/AlinaMoskieva">Moskieva Alina</a>
</p>